

spring:
  jackson:
    time-zone: GMT+8
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/DD?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
          username: root
          password: bjy653300
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://127.0.0.1:3306/contract?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
          username: root
          password: bjy653300
          driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        keep-alive: true

    dbcp2:
      fast-fail-validation:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


mybatis:
  table:
    auto: update
  model:
    pack: com.ynunicom.dd.contract.dingdingcontractrebuild.dao
  database:
    type: mysql
mybatis-plus:
  mapper-locations: classpath*:/dao/mapper/*/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml

server:
  port: 6051

dingding:
  manager-Id: ""
  viceManager-Id: ""
  legal-Dept-Id: ""
  financial-Dept-Id: ""
  nonceStr: "nice_peacefully_day"
  app-key: "dingpcgfojft6nw4ifdi"
  app-secret: "Crt31CokHxEOSKsuUxIWrZIAwcvdTgx0007KQRk8uTI5UbP8GLtdoviNvBkvfaGy"
  agent-id: "809746748"
  corp-Id: "dingc25328cad366b400a39a90f97fcb1e09"
  domain: "trump"
  start-process-instance-def-key: "ContractApplyForYnUnicomRebuild"
  start-process-filename: "dingdingContractRebuild.bpmn20.xml"
  alter-process-instance-def-key: "ContractContinue"
  alter-process-filename: "dingdingContractRebuildAlterApplication.bpmn20.xml"
  contract-saver-role-group: ""
  contract-saver-role: "contractSaverRole"
  contract-saver-role-id: "1444438399"
  super-user-role: "superUser"
