

spring:
  jackson:
    time-zone: GMT+8
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
            url: jdbc:oracle:thin:@ localhost:1521:ora12
            username: dingding
            password: Sun!837278
            driver-class-name: oracle.jdbc.OracleDriver
      druid:
        keep-alive: true

    dbcp2:
      fast-fail-validation:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB



mybatis:
  table:
    auto: update
  model:
    pack: com.ynunicom.dd.contract.dingdingcontractrebuild.dao
  database:
    type: oracle
mybatis-plus:
  mapper-locations: classpath*:/dao/mapper/*/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml

server:
  port: 6051
  servlet:
    context-path: /dingdingContractApi


dingding:
  manager-Id: "135659635720289701"
  viceManager-Id: "1007346500902290"
  legal-Dept-Id: "374810094"
  financial-Dept-Id: "121832263"
  nonceStr: "nice_peacefully_day"
  app-key: "dinguvfuy5bfafjt5n6w"
  app-secret: "qaJxau4MZHW7n9adonGMVGspqfbVxqXm3cxrvIAm_x88djfNQ119EPbhLLVqva7s"
  agent-id: "823649830"
  corp-Id: "ding380d36a7db53e69235c2f4657eb6378f"
  domain: "trump"
  start-process-instance-def-key: "ContractApplyForYnUnicomRebuild"
  start-process-filename: "dingdingContractRebuild.bpmn20.xml"
  alter-process-instance-def-key: "ContractContinue"
  alter-process-filename: "dingdingContractRebuildAlterApplication.bpmn20.xml"
  contract-saver-role-group: "1501076831"
  contract-saver-role: "contractSaverRole"
  contract-saver-role-id: "1501216246"
  super-user-role: "superUser"

flowable:
  database-schema-update: true
